export const UPDATE_LIFELINE = 'UPDATE_LIFELINE';
export const UPDATE_HEARTLINE = 'UPDATE_HEARTLINE';
export const UPDATE_HEADLINE = 'UPDATE_HEADLINE';
export const UPDATE_FATELINE = 'UPDATE_FATELINE';
